site_name: AI Systems Design From Scratch
site_url: https://aminblm.github.io/ai_systems_design_from_scratch
site_description: Rebuilding enterprise systems and AI from first principles.

theme:
  name: material
  palette: 
    - scheme: slate # Dark mode out of the box
      primary: teal
      accent: cyan
  features:
    - navigation.tabs
    - navigation.selections
    - content.code.copy

plugins:
  - search
  - blog:
    blog_dir: blog
    post_dit: blog/posts

nav:
  - Home: index.md 
  - Architecture Deep-Dives:
    - Custom Databases: architecture/databases.md
  - Engineering blog:
    - Blog Home: blog/index.md