title: AI Systems Design From First Principles
description: Rebuilding enterprise systems and AI from first principles.
url: https://aminblm.github.io/ai_systems_design_from_scratch
css: ../../ai_system_design/modules/site_generator/styles.css
author: Amin Boulouma
footer_text: AI Systems Design From First Principles
baseurl: ""